include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI interface for update-podkop
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-3.0
PKG_MAINTAINER:=Buktop

include $(TOPDIR)/feeds/luci/luci.mk

$(eval $(call BuildPackage,luci-app-update-podkop))